### ISSUE TITLE
Across desktops...

### ISSUE THREAD

**Issue by jaggzh** [Flupp/sticky-window-snapping#12]
So, I wanted to make this work across desktops.
Commenting out one line didn't work:
`
// if (c.desktop !== workspace.currentDesktop && !c.onAllDesktops) continue;
`
I had to also comment out the c.screen line:
`
// if (c.screen !== client.screen) continue;
`

I was going to add this as an option to a fork, but wanted to ask about the above change (which would be made into a condition of course), first; annnd, I didn't want to waste my time unless you thought it might be an acceptable PR if done properly.

**Comment by Flupp** [comment]
Just for clarification: You suggest an option that the script behaves as if all windows were on the same virtual desktop? So, for example, when there is a window covering the left half of the screen on virtual desktop 1 and a second window covering the right half of the screen on virtual desktop 2, then resizing one of the windows at the edge in the middle of the screen should affect the other window?

Sounds doable, however, I wonder about the use case.

**Comment by jaggzh** [comment]
Correct. Probably default off.
I often will drag windows to each half of the screen, with, say, some
reference window, on one side, pinned across desktops (a browser page or,
frequently, some video found while I work).

To the other side are other project windows, each on their own desktop, so
I now am able to have them all size along with the pinned one.
