### ISSUE TITLE
new release for plasma 5.22

### ISSUE THREAD

**Issue by tcanabrava** [Flupp/sticky-window-snapping#14]
the kde store still uses the release from 2018, since most users will install this via the get new stuff button, we should use a new release for that.

**Comment by Flupp** [comment]
I am not sure if I get your point. Do you refer to the unreleased commits https://github.com/Flupp/sticky-window-snapping/compare/v1.0...a65c31e137aa8e85c6dc06204394ef583acc7510 on `master`? These commits are pure code cleanup and should not affect the user. In my opinion they do not really justify a new release.

**Comment by tcanabrava** [comment]
That's true in theory, but theory never follows reality :)

A bit more background, I work together with @zzag and I realized the "sticky window snapping" that I use daily was not working. I verified that I have the latest version installed from the "get new stuff" so I start to debug what's happening.
New code entered on kwin and that changed how the javascript is read, zzag added code to fix that in 2019, but there's no release with that code yet:

This is what you get with the latest release:
kwin/scripts/sticky-window-snapping/contents/code/main.js:320: TypeError: Type error
kwin/scripts/sticky-window-snapping/contents/code/main.js:36: error: enabledCurrently is not defined

and the script doesn't work.

**Comment by zzag** [comment]
291bf5e is not simply a code cleanup. :) It ensures that the script will work with a js engine that properly supports strict mode. QtScriptEngine didn't have proper strict mode checks.

**Comment by Flupp** [comment]
Thanks for the heads-up. I’ve finally managed to publish a new release. Turns out, KWin 5.22 introduced also some other subtle changes to the JavaScript API that needed fixing in the script.

**Comment by ohyrans** [comment]
Don't want to open a seperate issue just yet - but is trying to figure out why it doesn't work on my system (Opensuse TW, Plasma 5.22.2, Framework 5.83, Wayland + Intel) and not certain its related to Sticky Window Snapping, but something else - hence commenting here...
Tried reinstalling it, enabling/reenabling, reboot etc. 

Is there a good way to get proper info about what may be going wrong to provide a better bug report?

**Comment by Flupp** [comment]
@ohyrans: I created the new issue #15 and replied to you there. Please continue the discussion in the new issue.
