### ISSUE TITLE
Don't work with Force Blur

### ISSUE THREAD

**Issue by vlad-mod** [Flupp/sticky-window-snapping#17]
this script don't work with Force Blur script (https://github.com/esjeon/kwin-forceblur)

**Comment by Flupp** [comment]
I just tried with both scripts, Force Blur and Sticky Window Snapping, enabled. I used Yakuake for checking if it works, and it does work for me.

Arch Linux
kwin 5.23.4-1
plasma-workspace 5.23.4-1
Force Blur 0.5 (from store)
Sticky window Snapping 1.0.1

Can you be a bit more specific about what is not working under which conditions?

**Comment by vlad-mod** [comment]
i just re enabled Force Blur, and now all works, bruh
