### ISSUE TITLE
Incompatible with nclarius/tile-gaps

### ISSUE THREAD

**Issue by fischer-felix** [Flupp/sticky-window-snapping#19]
I would like to have gaps between my windows, so I installed the [Window Gaps](https://github.com/nclarius/tile-gaps) KWin script, but it appears that sticky resizing does not work anymore with this enabled.
I don't know what side is causing the problem, hence opening an issue on both (see nclarius/tile-gaps#12).

**Comment by Flupp** [comment]
This is a known issue; @nclarius already created a pull request (#16). Unfortunately I have not found enough time yet to address this satisfactorily.

**Comment by fischer-felix** [comment]
Thanks for the heads-up! So far the fork works flawlessly for me, will report to the pr if there are any issues.

**Comment by nclarius** [comment]
After making the fork and PR it occurred to me that it should work without the modification as long as the threshold in the SWS configuration is set to no smaller than the gap size. This seems to do the job for me anyways, but if this didn't solve the problem for the OP but the fork did, I'll leave the PR open.
