### ISSUE TITLE
Idea: Instant sticking if there's already a non-default-sized tiled window.

### ISSUE THREAD

**Issue by J-Kappes** [Flupp/sticky-window-snapping#20]
Currently, if you
1. tile a window
2. alter its size
3. tile a window somewhere else
it doesn't stretch or squeeze to fill the available space and stick instantly. Wouldn't it be preferable, if it did?

**Comment by Flupp** [comment]
The script has no notion about tiling. It just considers lined-up window edges during resize regardless of how “messy” the windows are arranged apart from that and regardless of window overlaps. I’d like to keep that simple and easily predictable behavior.

Note that there are other scripts that focus on actual tiling: https://store.kde.org/browse?cat=210&tag=tiling&ord=rating
