### ISSUE TITLE
Incompatible with KWin Wayland

### ISSUE THREAD

**Issue by Alex-Bujorianu** [Flupp/sticky-window-snapping#22]
I noticed that this script was not compatible with KWin on Wayland when I tried it a few months ago. Is this still the case?

**Comment by Kishore96in** [comment]
It works on wayland for me with 

Operating System: Arch Linux
KDE Plasma Version: 5.25.5
KDE Frameworks Version: 5.98.0
Qt Version: 5.15.6
Kernel Version: 5.15.70-1-lts (64-bit)

**Comment by Flupp** [comment]
Thanks @Kishore96in, I trust your statement. Actually, I would be rather surprised if it works for the X11 version but not for the Wayland version of a particular KWin revision. If so, I’d consider this most probably a bug in KWin.

@Alex-Bujorianu: Please try again and ensure that you install the latest version of the script. If it still does not work for you, please provide the information from “About this System” in “System Settings” (there is a “Copy to Clipboard” button at the bottom).

**Comment by Alex-Bujorianu** [comment]
Hi @Flupp I retested it and it does work. Perhaps the incompatibility was on an older version of KDE or your script. With Plasma 5.26 it works as intended.
