### ISSUE TITLE
Not displaying blue overlay

### ISSUE THREAD

**Issue by rokups** [Flupp/sticky-window-snapping#7]
Is it possible to somehow disable this blue overlay when windows are being resized?

**Comment by Flupp** [comment]
Sorry, I do not know what blue overlay you mean. The script just changes the transparency of windows while resizing. This can be changed in the configuration dialog. Do you maybe have a blue background, which shines through while the windows are transparent? Do you use any desktop effect or another KWin script that might cause this?

**Comment by rokups** [comment]
Ah you are indeed right - its my background. Window that does not get resized becomes transparent to the point i thought it was some overlay. Where would i find configuration dialog?  I installed script through "Get New Scripts..." button in "KWin Scripts" section. It only has info button and no settings button like for example "Video Wall" has. I have version 1.0 installed.

**Comment by Flupp** [comment]
Please try the workaround from the description:

• If the configuration dialog is not reachable via “systemsettings”, then try the following command and restart “systemsettings”:

ln --relative --symbolic ~/.local/share/kwin/scripts/sticky-window-snapping/metadata.desktop ~/.local/share/kservices5/kwin-script-sticky-window-snapping.desktop

**Comment by rokups** [comment]
That worked. Settings did not apply without reboot. Thanks for the help and sorry for the noise :)
