### ISSUE TITLE
Ctrl + Shift + S is already reserved for “save as”

### ISSUE THREAD

**Issue by Flupp** [Flupp/sticky-window-snapping#9]
“Ctrl + Shift + S is already reserved for ‘save as’. It gets hijacked by the script. I would change the default to something else.” (comment on https://www.opendesktop.org/p/1112552/)

**Comment by nortexoid** [comment]
How about Ctrl+Meta+S?

**Comment by adrianinsaval** [comment]
> 
> 
> How about Ctrl+Meta+S?

+1

**Comment by WildEgo** [comment]
Would it be possible to just disable them by default as I don't plan to toggle it ever?
